config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  resources :landmarks, only: [:new, :create]
  resources :travels,   only: [:new, :create, :edit, :update, :destroy, :show]
  resources :users,      only: :show
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :authenticate_user!

  def new
    @travel_form = TravelForm.new
  end

  def create
    form_params = params[:travel_form]
    if form_params[:start_date].present?
      begin
        form_params[:start_date] = Date.parse(form_params[:start_date])
      rescue ArgumentError, Date::Error => e
        flash[:error] = "無効な日付形式: #{form_params[:start_date]}"
        render :new and return
      end
    end

    if form_params[:end_date].present?
      begin
        form_params[:end_date] = Date.parse(form_params[:end_date])
      rescue ArgumentError, Date::Error => e
        flash[:error] = "無効な日付形式: #{form_params[:end_date]}"
        render :new and return
      end
    end

    if form_params[:original_date].present?
      begin
        form_params[:original_date] = Date.parse(form_params[:original_date])
      rescue ArgumentError, Date::Error => e
        flash[:error] = "無効な日付形式: #{form_params[:original_date]}"
        render :new and return
      end
    end

    if form_params[:original_start_time].present?
      begin
        form_params[:original_start_time] = Time.parse(form_params[:original_start_time])
      rescue ArgumentError => e
        flash[:error] = "無効な時間形式: #{form_params[:original_start_time]}"
        render :new and return
      end
    end

    if form_params[:original_end_time].present?
      begin
        form_params[:original_end_time] = Time.parse(form_params[:original_end_time])
      rescue ArgumentError => e
        flash[:error] = "無効な時間形式: #{form_params[:original_end_time]}"
        render :new and return
      end
    end

    @travel_form = TravelForm.new(travel_form_params.merge(user_id: current_user.id))

    if @travel_form.save
      redirect_to "/"
    else
      render :new
    end
  end

  def edit
    # 編集するTripを取得
    @trip = Trip.find(params[:id])
    
    # フォームオブジェクトにデータを設定
    @travel_form = TravelForm.new(
      travel_name: @trip.travel_name,
      prefecture_id: @trip.prefecture_id,
      start_date: @trip.start_date,
      end_date: @trip.end_date,
      user_id: @trip.user_id,
      original_date: @trip.schedules.first&.date,
      original_start_time: @trip.schedules.first&.activities.first&.start_time,
      original_end_time: @trip.schedules.first&.activities.first&.end_time,
      original_location: @trip.schedules.first&.activities.first&.location,
      original_description: @trip.schedules.first&.activities.first&.description,
      additional_dates: @trip.schedules.pluck(:date),
      start_times: @trip.activities.pluck(:start_time),
      end_times: @trip.activities.pluck(:end_time),
      locations: @trip.activities.pluck(:location),
      descriptions: @trip.activities.pluck(:description)
    )
  end

  def update
    # Tripを取得
    @trip = Trip.find(params[:id])

    # フォームオブジェクトに編集されたデータをセット
    @travel_form = TravelForm.new(travel_form_params)
    @travel_form.trip = @trip # 既存のTripを設定

    # 更新処理の実行
    if @travel_form.update
      redirect_to trip_path(@trip), notice: '更新しました。'
    else
      flash.now[:alert] = '更新に失敗しました。'
      render :edit
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @schedules = @trip.schedules.includes(:activities)
  end

  private

  def travel_form_params
    params.require(:travel_form).permit(
      :travel_name, :prefecture_id, :start_date, :end_date, :user_id,
      :original_date, :original_start_time, :original_end_time, :original_location, :original_description,
      :start_time, :end_time, :location, :description,:date,
      additional_dates: {}, start_times: {}, end_times: {}, locations: {}, descriptions: {}
    )
  end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/edit.html.erb
<%= render "shared/second-header" %>

<% if @travel_form.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@travel_form.errors.count, "error") %> prohibited this travel from being saved:</h2>
    <ul>
    <% @travel_form.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @travel_form, url: travels_path, local: true do |f| %>
  <!-- 旅行の基本情報入力 -->
  <div class="form-text-wrap">
    <label class="form-text">旅行名</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.text_field :travel_name, id: "travel-code", placeholder: "題名", maxlength: "100" %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">都道府県名</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "select-box", id: "prefecture"}) %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">出発日</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.date_field :start_date, id: "travel-code", placeholder: "出発日" %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">帰宅日</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.date_field :end_date, id: "travel-code", placeholder: "帰宅日" %>
    </div>
  </div>

  <!-- 予定の入力フォーム -->
  <div id="form-segment">
    <div class="form-text-wrap">
      <label class="form-text">日にち</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.date_field :original_date, id: "travel-code", placeholder: "10月10日" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">開始時間</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.time_field :original_start_time, id: "travel-code", placeholder: "10:00" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">終了時間</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.time_field :original_end_time, id: "travel-code", placeholder: "11:00" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">場所</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.text_field :original_location, id: "travel-code", placeholder: "厳島神社" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">やること</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.text_area :original_description, id: "travel-code", placeholder: "○○で遊ぶ" %>
      </div>
    </div>
  </div>

  <!-- 保存ボタン -->
  <div class="keep-btn">
    <%= f.submit "保存する", class: "keep-red-btn", id: "button" %>
  </div>
<% end %>

app/views/travels/new.html.erb
<%= render "shared/second-header" %>

<% if @travel_form.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@travel_form.errors.count, "error") %> prohibited this travel from being saved:</h2>
    <ul>
    <% @travel_form.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @travel_form, url: travels_path, local: true do |f| %>
  <!-- 旅行の基本情報入力 -->
  <div class="form-text-wrap">
    <label class="form-text">旅行名</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.text_field :travel_name, id: "travel-code", placeholder: "題名", maxlength: "100" %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">都道府県名</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class: "select-box", id: "prefecture"}) %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">出発日</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.date_field :start_date, id: "travel-code", placeholder: "出発日" %>
    </div>
  </div>

  <div class="form-text-wrap">
    <label class="form-text">帰宅日</label><span class="indispensable">必須</span>
    <div class="field">
      <%= f.date_field :end_date, id: "travel-code", placeholder: "帰宅日" %>
    </div>
  </div>

  <!-- 予定の入力フォーム -->
  <div id="form-segment">
    <div class="form-text-wrap">
      <label class="form-text">日にち</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.date_field :original_date, id: "travel-code", placeholder: "10月10日" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">開始時間</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.time_field :original_start_time, id: "travel-code", placeholder: "10:00" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">終了時間</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.time_field :original_end_time, id: "travel-code", placeholder: "11:00" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">場所</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.text_field :original_location, id: "travel-code", placeholder: "厳島神社" %>
      </div>
    </div>

    <div class="form-text-wrap">
      <label class="form-text">やること</label><span class="indispensable">必須</span>
      <div class="field">
        <%= f.text_area :original_description, id: "travel-code", placeholder: "○○で遊ぶ" %>
      </div>
    </div>
  </div>

  <!-- 予定を追加するボタン -->
  <div>
    <button type="button" id="add-field-button">予定を追加</button>
  </div>

  <!-- 保存ボタン -->
  <div class="keep-btn">
    <%= f.submit "保存する", class: "keep-red-btn", id: "button" %>
  </div>
<% end %>

app/views/travels/show.html.erb
<%= render "shared/header" %>

<div class="travel-show">
  <div class="travel-box">
    <p>旅行名: <%= @trip.travel_name %></p>
    <p>出発日: <%= @trip.start_date %> ～ 終了日: <%= @trip.end_date %></p>
  </div>
  <% @schedules.each do |schedule| %>
    <div class="schedule">
      <h2>日程: <%= schedule.date %></h2>
    </div>

    <% if schedule.activities.exists? %>
      <% schedule.activities.each do |activity| %>
        <div class="activity">
          <p>開始時間: <%= activity.start_time %>~終了時間: <%= activity.end_time %></p>
          <p>場所: <%= activity.location %></p>
          <p>やること: <%= activity.description %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>


  <div class="action-buttons">
    <%= link_to '戻る', request.referrer, class: "travel-btn"  %>
    <%= link_to "編集する", edit_travel_path(@trip), class: "travel-btn" %>
    <%= link_to "削除", travel_path(@trip), data: { turbo_method: :delete }, class: "travel-btn" %>
  </div>
</div>