config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  resources :landmarks, only: [:new, :create]
  resources :travels,   only: [:new, :create, :edit, :update, :destroy, :show]
  resources :users,      only: :show
end

app/models/activitie.rb
class Activitie < ApplicationRecord
  belongs_to :schedule

  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :location,    presence: true
  validates :description, presence: true
  validates :schedule_id, presence: true

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :schedule

  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :location,    presence: true
  validates :description, presence: true
  validates :schedule_id, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: 'グルメ' },
    { id: 3, name: 'レジャー' }, 
    { id: 4, name: '宿泊' },
    { id: 5, name: 'その他' }, 
  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  has_many :posts
  has_one_attached :image

  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank"}
  validates :city,          presence: true
  
  validate  :valid_name
  validate  :valid_street_address

  private

  def valid_name
    unless name.present? && name =~ /\A.{1,100}\z/
    errors.add(:name, "Please enter name in 100 characters or less")
    end
  end

  def valid_street_address
    unless street_address.present? && street_address =~ /\A.{1,20}\z/
    errors.add(:street_address, "Please enter street address in 20 characters or less")
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true

  validates :user_id, uniqueness: { scope: :post_id, message: "You have already liked this post." }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to       :user
  belongs_to       :landmark
  has_one_attached :image
  has_many         :likes

  validates :title,       presence: true
  validates :body,        presence: true
  validates :category_id, numericality: { other_than: 1, message: "can't be blank"}
  validates :status_id,   numericality: { other_than: 1, message: "can't be blank"}
  validates :score_id,    numericality: { other_than: 1, message: "can't be blank"}

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '福島県' }, { id: 7, name: '秋田県' },
    { id: 8, name: '山形県' },
    { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' }, { id: 13, name: '東京都' }, { id: 14, name: '千葉県' }, 
    { id: 15, name: '神奈川県' },
    { id: 16, name: '長野県' }, { id: 17, name: '山梨県' }, { id: 18, name: '静岡県' },
    { id: 19, name: '愛知県' }, { id: 20, name: '岐阜県' }, { id: 21, name: '新潟県' }, 
    { id: 22, name: '富山県' }, { id: 23, name: '石川県' }, { id: 24, name: '福井県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' }, { id: 27, name: '大阪府' }, { id: 28, name: '奈良県' },
    { id: 29, name: '三重県' }, { id: 30, name: '和歌山県' }, { id: 31, name: '兵庫県' },
    { id: 32, name: '岡山県' }, { id: 33, name: '広島県' }, { id: 34, name: '山口県' }, 
    { id: 35, name: '島根県' }, { id: 36, name: '鳥取県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '徳島県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '大分県' }, { id: 43, name: '佐賀県' },
    { id: 44, name: '長崎県' }, { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' },
    { id: 47, name: '熊本県' }, { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :landmarks
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :trip
  has_many   :activities

  validates :date,    presence: true
  validates :trip_id, presence: true
end

app/models/score.rb
class Score < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '1' },
    { id: 3, name: '2' }, 
    { id: 4, name: '3' },
    { id: 5, name: '4' }, 
    { id: 6, name: '5' }
  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '一人旅' }, 
    { id: 3, name: '友達と' }, 
    { id: 4, name: '恋人と' },
    { id: 5, name: '家族と' }, 
    { id: 6, name: '子連れ' },
    { id: 7, name: 'その他' }

  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :schedules
  belongs_to :user
  
  validates :travel_name, presence: true
  validates :start_date,  presence: true
  validates :end_date,    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  has_many :likes
  has_many :trips
  has_many :travels

  validates :nickname,     presence: true
  validates :birth_day,    presence: true
  validate  :validate_password_format, if: -> { password.present? }
  validate  :valid_phone_number

  private

  def validate_password_format
    unless password =~ /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
      errors.add(:password, 'must include both letters and numbers')
    end
  end

  def valid_phone_number
    unless phone_number.present? && phone_number =~ /\A\d{10,11}\z/
      errors.add(:phone_number, "Please enter a valid 10-digit or 11-digit phone number")
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landmarks_helper.rb
module LandmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabimemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to "tamimemo","/", class: "top-icon" %>
    <%#= link_to image_tag("tabimemo", class:"top-icon"), "/" %>
  </div>
    <ul class='lists'>
      <% if user_signed_in? %>
         <li><%= link_to current_user.nickname, user_path(current_user), class: "user-nickname" %></li>
         <li><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout"  %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_like.html.erb
<% if user_signed_in? && post.liked_by?(current_user)%>
  <%=link_to "いいね済", post_likes_path(post.id),  data: { turbo_method: :delete }, class: "post_likes", remote: true %>
<% else %>
  <%=link_to "いいねする", post_likes_path(post.id), data: { turbo_method: :post }, class: "post_likes", remote: true %>
<% end %>

app/views/shared/_second-header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to "tamimemo","/", class: "top-icon" %>
  </div>
</header>