config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  resources :landmarks, only: [:new, :create]
  resources :travels,   only: [:new, :create, :edit, :update, :destroy, :show]
  resources :users,      only: :show
end

app/models/activitie.rb
class Activitie < ApplicationRecord
  belongs_to :schedule

  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :location,    presence: true
  validates :description, presence: true
  validates :schedule_id, presence: true

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :schedule

  validates :start_time,  presence: true
  validates :end_time,    presence: true
  validates :location,    presence: true
  validates :description, presence: true
  validates :schedule_id, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: 'グルメ' },
    { id: 3, name: 'レジャー' }, 
    { id: 4, name: '宿泊' },
    { id: 5, name: 'その他' }, 
  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  has_many :posts
  has_one_attached :image

  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank"}
  validates :city,          presence: true
  
  validate  :valid_name
  validate  :valid_street_address

  private

  def valid_name
    unless name.present? && name =~ /\A.{1,100}\z/
    errors.add(:name, "Please enter name in 100 characters or less")
    end
  end

  def valid_street_address
    unless street_address.present? && street_address =~ /\A.{1,20}\z/
    errors.add(:street_address, "Please enter street address in 20 characters or less")
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true

  validates :user_id, uniqueness: { scope: :post_id, message: "You have already liked this post." }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to       :user
  belongs_to       :landmark
  has_one_attached :image
  has_many         :likes

  validates :title,       presence: true
  validates :body,        presence: true
  validates :category_id, numericality: { other_than: 1, message: "can't be blank"}
  validates :status_id,   numericality: { other_than: 1, message: "can't be blank"}
  validates :score_id,    numericality: { other_than: 1, message: "can't be blank"}

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '福島県' }, { id: 7, name: '秋田県' },
    { id: 8, name: '山形県' },
    { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' }, { id: 13, name: '東京都' }, { id: 14, name: '千葉県' }, 
    { id: 15, name: '神奈川県' },
    { id: 16, name: '長野県' }, { id: 17, name: '山梨県' }, { id: 18, name: '静岡県' },
    { id: 19, name: '愛知県' }, { id: 20, name: '岐阜県' }, { id: 21, name: '新潟県' }, 
    { id: 22, name: '富山県' }, { id: 23, name: '石川県' }, { id: 24, name: '福井県' },
    { id: 25, name: '滋賀県' },
    { id: 26, name: '京都府' }, { id: 27, name: '大阪府' }, { id: 28, name: '奈良県' },
    { id: 29, name: '三重県' }, { id: 30, name: '和歌山県' }, { id: 31, name: '兵庫県' },
    { id: 32, name: '岡山県' }, { id: 33, name: '広島県' }, { id: 34, name: '山口県' }, 
    { id: 35, name: '島根県' }, { id: 36, name: '鳥取県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '徳島県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '大分県' }, { id: 43, name: '佐賀県' },
    { id: 44, name: '長崎県' }, { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' },
    { id: 47, name: '熊本県' }, { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :landmarks
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :trip
  has_many   :activities

  validates :date,    presence: true
  validates :trip_id, presence: true
end

app/models/score.rb
class Score < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '1' },
    { id: 3, name: '2' }, 
    { id: 4, name: '3' },
    { id: 5, name: '4' }, 
    { id: 6, name: '5' }
  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, 
    { id: 2, name: '一人旅' }, 
    { id: 3, name: '友達と' }, 
    { id: 4, name: '恋人と' },
    { id: 5, name: '家族と' }, 
    { id: 6, name: '子連れ' },
    { id: 7, name: 'その他' }

  ]
  include ActiveHash::Associations
  has_many :posts

end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :schedules
  belongs_to :user
  
  validates :travel_name, presence: true
  validates :start_date,  presence: true
  validates :end_date,    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  has_many :likes
  has_many :trips
  has_many :travels

  validates :nickname,     presence: true
  validates :birth_day,    presence: true
  validate  :validate_password_format, if: -> { password.present? }
  validate  :valid_phone_number

  private

  def validate_password_format
    unless password =~ /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
      errors.add(:password, 'must include both letters and numbers')
    end
  end

  def valid_phone_number
    unless phone_number.present? && phone_number =~ /\A\d{10,11}\z/
      errors.add(:phone_number, "Please enter a valid 10-digit or 11-digit phone number")
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only:[:edit, :update, :destroy]

  def index
    landmark_ids = Landmark.where(prefecture_id: params[:prefecture_id]).pluck(:id)
    @posts = Post.includes(:landmark).where(landmark_id: landmark_ids)
    @prefecture = Prefecture.find(params[:prefecture_id])
    #旅のしおり機能のため
    @trips = Trip.where(prefecture_id: params[:prefecture_id])
    #/旅のしおり機能のため
    if landmark_ids.any?
      @landmark = Landmark.find(landmark_ids.first)
    else
      @landmark = nil
    end
  end

  def new
    @post = Post.new
    @landmarks = Landmark.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to "/", notice: 'Post was successfully created.'
    else
      @landmarks = Landmark.all
      render :new
    end
  end

  def show
  end

  def edit
    @landmarks = Landmark.all
  end
  
  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.includes(:user, :landmark).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :title, :body,:status_id, :category_id, :score_id, :landmark_id, :user_id)
  end

  def correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landmarks_helper.rb
module LandmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<%= render "shared/second-header" %>
<div class="posts-main">
  <h2 class="posts-title">旅行情報登録</h2>
  <%= form_with model: @post, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"post-image" %>
      </div>
    </div>
    <%# /画像 %>
    <div class="weight-bold-text">
      どこへ
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:landmark_id, @landmarks, :id, :name, {}, {class:"select-box", id:"post-landmark"}) %>
    <div class="weight-bold-text">
      誰と
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"post-status"}) %>
    <div class="weight-bold-text">
      カテゴリー
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
    <div class="weight-bold-text">
      おすすめ度
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:score_id, Score.all, :id, :name, {}, {class:"select-box", id:"post-score"}) %>
    <%# 主題と内容 %>
    <div class="new-posts">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"post-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :body, class:"posts-text", id:"post-info", placeholder:"例）北海道の函館山に行きました。夜の夜景を見るためにロープウェイに乗りました。そこから見る景色は最高でした！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /主題と内容 %>

    <%# 下部ボタン %>
    <div class="btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', '/', class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render "shared/header" %>


  <h1 class="top-title"><%= @prefecture.name %></h1>
  <div class="main-body">
    <div class="left-body">
      <div class="post-top-title">旅行情報</div>
      <% @posts.each do |post| %>
        <%= link_to post_path(post) do %>
        <div class="post">
          <div class="post-top">
            <div class='post-img-content'>
              <% if post.image.present? %>
                <%= image_tag post.image, class: "post-img" %>
              <% else %>
                <%= image_tag'sample.png', class: "post-img" %>
              <% end %>
            </div>
            <div class="post-content">
              <div class="post-content-main">
                <div class="post-content-top">
                  <div class="post-status"><%= Status.find(post.status_id).name %>/</div>
                  <div class="post-score">おすすめ度：<%= Score.find(post.score_id).name %></div>
                  <div class="post-category">/<%= Category.find(post.category_id).name %></div>
                </div>
                <div class="post-title"><%= post.title %></div>
              </div>
            </div>
          </div>
          <div class="post-content-info">
            <div class="post-body"><%= post.body %></div>
            <div class="post-content-info-sub">
              <div class="post-user-nickname">作成者:<%= post.user.nickname %></div>
              <div id="like-btn<%= post.id %>">
                <%= render partial: "likes/like", locals: { post: post } %>
              </div>
            </div>
            <div class="post-created-at"><%= post.created_at %></div>
          </div>


        </div>
        <% end %>
      <% end %>
    </div>
    <div class="right-body">
      <h2 class="travel-top-title">旅のしおり</h2>
      <% if @trips.any? %>
        <% @trips.each do |trip| %>
          <%= link_to travel_path(trip) do %>
            <div class="travel-plan">
              <p class="travel-name">旅行名：<%= trip.travel_name %></p>
              <p class="travel-date"><%= trip.start_date %>～<%= trip.end_date %></p>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>No trips found for the selected prefecture_id.</p>
      <% end %>
    </div>
  </div>
  <%= link_to(new_landmark_path, class: 'landmark-btn') do %>
    <span class='landmark-btn-text'>観光地<br>登録</span>
    <%= image_tag 'travel.png' , size: '185x50' ,class: "landmark-btn-icon" %>
  <% end %>
  <%= link_to(new_travel_path, class: 'plan-btn') do %>
    <span class='plan-btn-text'>旅のしおり<br>作成</span>
    <%= image_tag 'plan.png' , size: '185x50' ,class: "plan-btn-icon" %>
  <% end %>
  <%= link_to(new_post_path, class: 'new-btn') do %>
    <span class='new-btn-text'>旅行情報<br>投稿</span>
    <%= image_tag 'travel.png' , size: '185x50' ,class: "new-btn-icon" %>
  <% end %>

app/views/posts/new.html.erb
<%= render "shared/second-header" %>
<div class="posts-main">
  <h2 class="posts-title">旅行情報登録</h2>
  <%= form_with model: @post, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"post-image" %>
      </div>
    </div>
    <%# /画像 %>
    <div class="weight-bold-text">
      どこへ
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:landmark_id, @landmarks, :id, :name, {}, {class:"select-box", id:"post-landmark"}) %>
    <div class="weight-bold-text">
      誰と
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"post-status"}) %>
    <div class="weight-bold-text">
      カテゴリー
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
    <div class="weight-bold-text">
      おすすめ度
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:score_id, Score.all, :id, :name, {}, {class:"select-box", id:"post-score"}) %>
    <%# 主題と内容 %>
    <div class="new-posts">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"post-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :body, class:"posts-text", id:"post-info", placeholder:"例）北海道の函館山に行きました。夜の夜景を見るためにロープウェイに乗りました。そこから見る景色は最高でした！" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /主題と内容 %>

    <%# 下部ボタン %>
    <div class="btn-contents">
      <%= f.submit "投稿する", class:"post-btn" %>
      <%=link_to 'もどる', '/', class:"post-btn" %>
    </div>
    <%# /下部ボタン %>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post-show">
  <div class="post-box">
    <div class="post-img-content">
      <% if @post.image.present? %>
        <%= image_tag @post.image, class: "post-img" %>
        <% else %>
        <%= image_tag'sample.png', class: "post-img" %>
       <% end %>
    </div>
    <div class="post-box-title">    <%= @post.title %></div>
    <div class="post-box-body">     <%= @post.body %></div>
    <div class="post-box-status">   <%= Status.find(@post.status_id).name %></div>
    <div class="post-box-category"> カテゴリー：<%= Category.find(@post.category_id).name %></div>
    <div class="post-box-score">    おすすめ度：<%= Score.find(@post.score_id).name %></div>
    <%= link_to "戻る", request.referrer, class: "back-btn" %>
    <%= link_to "編集する", edit_post_path(@post), class: "post-red-btn" %>
    <%= link_to "削除", post_path(@post), data: { turbo_method: :delete }, class: "post-destroy" %>
  </div>
</div>